spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tiendageyase
    username: posgres
    password: posgres
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true